### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 0xebfehat**
Your tool inspired me, and created pyw to make process with cmdline based on your code.
This does not use timeline csv but Agent Event - process events.

### CODE REVIEW

**Comment by Beercow** [comment]
I am receiving the following error. Any ideas?

C:/Users/beercow/Desktop/export.csv
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "Redline1.20 Process Tree Report-cmdline.pyw", line 74, in <lambda>
    b2 = Button(root, text='Run', command=lambda: show_entry_fields(getFile.get()))
  File "Redline1.20 Process Tree Report-cmdline.pyw", line 62, in show_entry_fields
    g1.render(u'temp', view=True, cleanup=True)
  File "C:\Users\beercow\Virtualenv\redline\Lib\site-packages\graphviz\files.py", line 144, in render
    filepath = self.save(filename, directory)
  File "C:\Users\beercow\Virtualenv\redline\Lib\site-packages\graphviz\files.py", line 123, in save
    data = text_type(self.source)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 135878: ordinal not in range(128)

**Comment by 0xebfehat** [comment]
Thank you for your feedback.
It seems to be python default encoding.

Can you try the following step?

Create sitecustomize.py in the python site-package directory.

If you install python in default place, it is c:\Python27\Lib\site-packages

Write the following in sitecustomize.py

import sys
sys.setdefaultencoding('utf-8')



2017/05/25 23:27、Brian Maloney <notifications@github.com<mailto:notifications@github.com>> のメッセージ:


I am receiving the following error. Any ideas?

C:/Users/beercow/Desktop/export.csv
Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Python27\lib\lib-tk\Tkinter.py", line 1537, in call
return self.func(*args)
File "Redline1.20 Process Tree Report-cmdline.pyw", line 74, in
b2 = Button(root, text='Run', command=lambda: show_entry_fields(getFile.get()))
File "Redline1.20 Process Tree Report-cmdline.pyw", line 62, in show_entry_fields
g1.render(u'temp', view=True, cleanup=True)
File "C:\Users\beercow\Virtualenv\redline\Lib\site-packages\graphviz\files.py", line 144, in render
filepath = self.save(filename, directory)
File "C:\Users\beercow\Virtualenv\redline\Lib\site-packages\graphviz\files.py", line 123, in save
data = text_type(self.source)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 135878: ordinal not in range(128)

**Comment by Beercow** [comment]
Thanks. Yeah. I figured that out. I added the following lines to the code:
reload(sys)  
sys.setdefaultencoding('utf8')

Just trying to figure out a way to move the command line from the edge label into the node. Or a cleaner way of doing it. That and I want to see what the difference between the timeline and process events look like. :) Nice job.

**Comment by 0xebfehat** [comment]
Thank you. Yes, me, too. I try to find a way to make the graph clearer.

**Comment by Beercow** [comment]
I've updated the file to create a cleaner graph. Let me know what you think.

**Comment by 0xebfehat** [comment]
This is another option I was wondering, this is much better :)

**Comment by Beercow** [comment]
From the change I made, Inoticed it only gives the last command instead of all of them. I have a fix for that. Will post later and see what you think before merging. Do you have any idea on how to make it so the GUI doesn't lock up? Thinking about adding some sort of indicator but not exactly sure how to go about doing it.

**Comment by Beercow** [comment]
Update. Let me know what you think of the output.

**Comment by 0xebfehat** [comment]
Thanks. I will check it.

**Comment by 0xebfehat** [comment]
I found that cmdline is put inside the parent process box in some cases. I tried to find another way with graphviz, however I feel  it is complicated to manage process relationships with cmdline in graphviz.
Based on that, I think command line over edge label is the best (not elaborated though) 
I feel that I need to look into another graph tool like neo4js when I have time.
Anyway, your original python is nice. 

If you don't mind, I will close this pull request.

**Pull request merged**
